version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: go-gorm-example
    container_name: gorm-api
    
    